services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    restart: unless-stopped
    container_name: jbtronics-demo # A custom name to be used in build scripts
    depends_on:
      - db # requires the database service to be available
    ports:
      - "6680:80" # the service will be available in my browser at http://localhost:6680
    volumes:
      - .:/var/www/project # all files in current directory will also be available in the container, allowing you to update the source code with your IDE
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf:ro # Override the default apache vhost file to ensure that the symfony application is served by default
      - ./.bashrc:/root/.bashrc:ro # Bash aliases
      # the contents of 000-default.conf is obtained from https://symfony.com/doc/current/setup/web_server_configuration.html, with modifications applied to match folder locations

  db: # The service name or host to the database
    image: mariadb:10.6
    restart: unless-stopped # ensures that the service automatically runs as soon as Docker starts up
    command: "--default-authentication-plugin=mysql_native_password" # Fixes the "mysqli::real_connect(): (HY000/1524): Plugin 'mysql_native_password' is not loaded" error
    volumes:
      - mysql_data:/var/lib/mysql # persistent volume to ensure that database changes are retained during container restarts
    environment:
      # I do not normally use root to log in to MySQL
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER: app_development
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: jbtronics

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "6681:80" # the service will be available in my browser at http://localhost:6681
    depends_on:
      - db
    environment:
      PMA_HOST: db # must match the service name used for the MySQL database above
      PMA_USER: app_development # must match the value of MYSQL_USER above
      PMA_PASSWORD: password # must match the value of MYSQL_PASSWORD above

volumes:
  mysql_data: # the volume name used in db:volumes above
